# Generated by Django 6.0.6 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_chatbox',
            field=models.BooleanField(default=False),
        ),
    ]
